## Mediation

Original routine used in vignette

```{r eval=FALSE}
cmst
  cmst1
    fitFunction
    calcICs
    calcZ
    normIUCMST
    binomIUCMST
    normJointIUCMST
  model_setup
```


Routine now used in R/qtl2shiny: `mediate1_test`

```{r eval=FALSE}
mediate1_test
  cmst_pheno
    cmst_default
      med_fits
        fitFunction
      combo_models
      combine_models
      testFunction <- wilcIUCMST, binomIUCMST, normJointIUCMST, normIUCMST
        calcZ
          calcICs
        calcShat
        left_right
```

```{r}
mediation_triad
  med_fits
    fitFunction
  label_fn = qtl2pattern::pattern_label
  group_fn = qtl2pattern::pattern_sdp
```

Utilities

```{r eval=FALSE}
fitQtl2 uses qtl2::fit1
common_data (from qtl2pattern)
covar_df_mx (from qtl2pattern)
wh_sex(from qtl2pattern)
```

## Scatterplot

```{r}
med_name <- sum_med$id[1]
mediator <- med_ls[[1]][, med_name, drop = FALSE]
driver_name <- (med_ls[[2]] %>% 
  filter(id == med_name))$driver
driver <- driver_med[,, driver_name]
```

```{r}
sdp <- snpprobs_obj$snpinfo$sdp[which.min(abs(snpprobs_obj$snpinfo$pos - sum_med$pos[1]))]
```

```{r}
scat_dat <- CausalMST::mediation_triad(
  target = pheno_data, 
  mediator = mediator,
  driver = driver, 
  covar_tar = covar, 
  covar_med = med_ls$covar,
  kinship = kinship[[1]], 
  sdp = sdp, 
  allele = TRUE)
```
